[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MechanicalMindDependencyAI"
version = "1.0.0"
description = "Description of your project"
authors = [
    { name = "Your Name", email = "your-email@example.com" },
]
dependencies = [
    # Add dependencies here
]
