Step: Run dependency scan using MechMind AI Dependency Action
   - Performs a strict dependency analysis
   - Automatically fixes common issues
   - name: Dependency Scan 
        id: dependency-scan
      buses: mechmind/ai-dependency-action@v3.0.1
        with:
   strict-mode: true
    auto-fix: true
# Optional: Report issues if any were found
 - name: Report Issues
     if: steps.dependency-scan.outputs.issues_found == 'true'
    run: echo "Dependency issues found! Review the scan results."
