name: Dependency Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
     
      - name: Dependency Scan
         id: dependency-scan
       uses: mechmind/ai-dependency-action@v3.0.1
      with:
    strict-mode: true
    auto-fix: true
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Optional: Report issues if any were found
- name: Report Issues
  if: steps.dependency-scan.outputs.issues_found == 'true'
  run: echo "Dependency issues found! Review the scan results."
