# .github/workflows/main.yml

name: Procesamiento de Reportes de Dependencias

on:
  workflow_run:
    workflows: ["Análisis de Dependencias"]
    types:
      - completed

jobs:
  procesar-reportes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          name: dependency-report
          path: ./reportes/
          
      - name: Procesar artefactos
        run: |
          echo "Procesando artefactos descargados..."
          python nucleo_ai/procesador_artefactos.py \
            --entrada "./reportes" \
            --salida ./reportes_finales/
            
      - name: Subir reportes procesados
        uses: actions/upload-artifact@v3
        with:
          name: reportes-finales
          path: ./reportes_finales/
