name: Dependency Analysis Processor

on:
  workflow_run:
    workflows: ["Dependency Analysis"]
    types:
      - completed

jobs:
  process-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: 'report-*.json'
          path: ./custom_reports/
          merge-multiple: true
          github-token: ${{ secrets.CI_CD_TOKEN }}

      - name: Upload processed artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency-report
          path: ./reports/
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ARTIFACT_ACCESS_TOKEN }}

      - name: Process Artifacts
        run: |
          echo "Processing downloaded artifacts..."
          python ai_core/artifact_processor.py \
            --input "${{ runner.temp }}/artifacts" \
            --output ./reports/
