-- name:
   uses: actions/download-artifact@v4.2.1
       with:
        pattern: 'report-*.json'
         path: ./custom_reports/
          merge-multiple: true
           github-token: ${{ secrets.CI_CD_TOKEN }}
            repository: mechmind-dwv/-MechanicalMind-Dependency-AI-v2.0-
              run-id: ${{ github.event.workflow_run.id }}
on:
  workflow_run:
    workflows: ["Dependency Analysis"]
    types:
      - completed

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Download Specific Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: dependency-report
        path: ${{ runner.temp }}/artifacts
        github-token: ${{ secrets.GH_ARTIFACT_ACCESS_TOKEN }}

    - name: Process Artifacts
      run: |
        echo "Processing downloaded artifacts..."
        python ai_core/artifact_processor.py \
          --input "${{ runner.temp }}/artifacts" \
          --output ./reports/
[![.github/workflows/main.yml](https://github.com/mechmind-dwv/-MechanicalMind-Dependency-AI-v2.0-/actions/workflows/main.yml/badge.svg)](https://github.com/mechmind-dwv/-MechanicalMind-Dependency-AI-v2.0-/actions/workflows/main.yml)
