name: Runner Maintenance and Health Check
on:
  schedule:
    - cron: '0 3 * * *'  # Ejecución diaria a las 3 AM UTC
  workflow_dispatch:     # Permite ejecución manual

jobs:
  cleanup:
    name: Cleanup Offline Runners
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clean up offline runners
        uses: actions/cleanup-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          remove-token: ${{ secrets.GITHUB_TOKEN }}
          exclude-running: true  # No eliminar runners en uso
          min-age-days: 1        # Solo runners inactivos >1 día
          dry-run: false         # Cambiar a true para pruebas

  health-check:
    name: Runner Health Check
    needs: cleanup  # Depende del job de limpieza
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space
        run: df -h
        
      - name: Check memory usage
        run: free -m
        
      - name: Check CPU cores
        run: nproc
        
      - name: Check runner status
        run: |
          echo "::group::Runner Status"
          echo "Runner version: ${{ runner.version }}"
          echo "OS: ${{ runner.os }}"
          echo "::endgroup::"
          
      - name: Check GitHub Actions service status
        run: |
          STATUS=$(curl -s https://www.githubstatus.com/api/v2/status.json | jq -r '.status.description')
          echo "GitHub Actions Status: $STATUS"
