##[debug]Starting: Set up job
Current runner version: '2.323.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
##[debug]Primary repository: mechmind-dwv/-MechanicalMind-Dependency-AI-v3.0-
Prepare workflow directory
##[debug]Creating pipeline directory: '/home/runner/work/-MechanicalMind-Dependency-AI-v3.0-'
##[debug]Creating workspace directory: '/home/runner/work/-MechanicalMind-Dependency-AI-v3.0-/-MechanicalMind-Dependency-AI-v3.0-'
##[debug]Update context data
##[debug]Evaluating job-level environment variables
##[debug]Evaluating job container
##[debug]Evaluating job service containers
##[debug]Evaluating job defaults
Prepare all required actions
Getting action download info
Error: Missing download info for actions/runner-cleanup@v2
##[debug]System.Exception: Missing download info for actions/runner-cleanup@v2
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
##[debug]   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
##[debug]Finishing: Set up job
